---
deployment:
  tasks:
    - export DEPLOYPATH=/home/praja431/portfolio.prajapatidhrv.com
    - cd $DEPLOYPATH
    - git pull origin main
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - npm install
    - npm run build
    - php artisan migrate --force
    - php artisan db:seed --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
